x-environment: &x-environment
  PROXY_SERVER: http://bobcatdev.library.nyu.edu:80
  NODE_ENV: ${NODE_ENV-development}
  VIEW:
  VE:
  SAML:
  CAS:
  PACK:

x-defaults: &x-defaults
  build:
    context: .
    cache_from:
    - primo-explore-devenv
    - quay.io/nyulibraries/primo-explore-devenv
    - quay.io/nyulibraries/primo-explore-devenv:$BRANCH_NO_SLASH
  image: primo-explore-devenv
  environment:
    <<: *x-environment
  ports:
    - 8004:8004
    - 3001:3001
  # volumes:
  #   - ./primo-explore:/app/primo-explore
  #   - ./packages:/app/packages

version: '3.7'
services:
  web:
    <<: *x-defaults
    environment:
      <<: *x-environment
  create-package:
    <<: *x-defaults
    environment:
      <<: *x-environment
      NODE_ENV: ${NODE_ENV-staging}
    command: yarn create-package


  web-gulp-legacy:
    <<: *x-defaults
    build:
      context: .
      dockerfile: gulp/Dockerfile
    image: primo-explore-devenv-gulp
    ports:
    - 8003:8003
    - 3001:3001
  create-package-gulp-legacy:
    <<: *x-defaults
    build:
      context: .
      dockerfile: gulp/Dockerfile
    image: primo-explore-devenv-gulp
    environment:
      NODE_ENV: ${NODE_ENV-staging}
    command: yarn create-package --view=${VIEW}
    depends_on:
      - web-gulp-legacy

